AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  EnvDBHost:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /rails-lambda/DB_HOST
  EnvDBUser:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /rails-lambda/DB_USER
  EnvDBPassword:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /rails-lambda/DB_PASSWORD
  EnvRailsSecret:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /rails-lambda/SECRET_KEY_BASE

Resources:
  RailsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: RailsApp
      Handler: lambda.handler
      Runtime: ruby2.5
      CodeUri: "./"
      MemorySize: 1024
      Timeout: 500
      Environment:
        Variables:
          RAILS_SERVE_STATIC_FILES: true
          RAILS_LOG_TO_STDOUT: true
          RAILS_ENV: production
          BOOTSNAP_CACHE_DIR: '/tmp/.bootsnap/'
          DB_HOST: !Ref EnvDBHost
          DB_NAME: rails-lambda-pg
          DB_USER: !Ref  EnvDBUser
          DB_PASSWORD: !Ref EnvDBPassword
          SECRET_KEY_BASE: !Ref EnvRailsSecret
